esphome:
  name: barn_freezer_test
  platform: ESP8266
  board: huzzah

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dallas:
  - pin: 13
    update_interval: 60s

sensor:
  - platform: dallas
    # Find this value by running your device with this sensor node commented out
    # It will show a Dallas Address in the logs
    #address: 0xA101193A71D7BF28
    name: "Temperature"
    id: "temperature"
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"

binary_sensor:
  - platform: gpio
    name: "USB Power"
    pin: 
      number: 12
